using System;
using System.Collections.Generic;

namespace LocalAchievements
{
    // UI-only translations. Rule IDs, file contents and SuccessStory records are
    // intentionally never translated. Longer phrases run first so messages built
    // from several literals keep their context and paths untouched.
    internal static class UiLanguage
    {
        public static bool English;
        private static readonly List<KeyValuePair<string, string>> Phrases = CreatePhrases();

        public static string T(string value)
        {
            if (!English || String.IsNullOrEmpty(value)) { return value; }
            foreach (KeyValuePair<string, string> phrase in Phrases)
            {
                value = value.Replace(phrase.Key, phrase.Value);
            }
            return value;
        }

        private static KeyValuePair<string, string> P(string chinese, string english)
        {
            return new KeyValuePair<string, string>(chinese, english);
        }

        private static List<KeyValuePair<string, string>> CreatePhrases()
        {
            var items = new List<KeyValuePair<string, string>>
            {
                P("本地成就自动解锁 - 当前无法弹窗", "Automatic Local Achievements - Pop-ups unavailable"),
                P("本地成就自动解锁 - 写入前确认", "Automatic Local Achievements - Confirm changes"),
                P("本地成就自动解锁 - 健康状态", "Automatic Local Achievements - Source health"),
                P("本地成就自动解锁", "Automatic Local Achievements"),
                P("导入自动成就规则文件…", "Import automatic achievement rule file..."),
                P("自动识别模拟器并配置规则", "Detect emulator and configure rules"),
                P("文件补全", "File completion"),
                P("GSE 成就定义…", "GSE achievement definitions..."),
                P("RUNE/CODEX 成就接口…", "RUNE/CODEX achievement interface..."),
                P("界面语言已更改。现在重启 Playnite 以应用新语言吗？", "The interface language has changed. Restart Playnite now to apply it?"),
                P("重启 Playnite？", "Restart Playnite?"),
                P("当前 Playnite 版本未提供可调用的重启功能。", "This Playnite version does not expose a callable restart function."),
                P("自动重启失败，请手动重启 Playnite：", "Automatic restart failed. Please restart Playnite manually: "),
                P("检查并补全 GSE 成就定义…", "Check and complete GSE achievement definitions..."),
                P("检查并补全 RUNE/CODEX 成就接口…", "Check and complete RUNE/CODEX achievement interface..."),
                P("查看成就来源健康状态", "View achievement source health"),
                P("测试成就弹窗", "Test achievement pop-up"),
                P("测试成就", "Test achievement"),
                P("用于预览成就通知的位置和音效。", "Preview the achievement notification position and sound."),
                P("立即补扫并同步本地成就", "Rescan and synchronize local achievements now"),
                P("移除自动成就规则", "Remove automatic achievement rules"),
                P("自动成就规则文件 (*.json)|*.json", "Automatic achievement rule file (*.json)|*.json"),
                P("已为“", "Rules for \""),
                P("”导入规则。下次通过 Playnite 启动此游戏时会自动运行。\n\n如需同步至 SuccessStory，请先在 SuccessStory 中手动添加或导入该游戏的成就列表。规则中的成就 ID 必须与 SuccessStory 的 ApiName 相同。", "\" have been imported. They will run the next time Playnite launches this game.\n\nTo sync with SuccessStory, add or import the game's achievement list there first. Rule IDs must match SuccessStory ApiName IDs."),
                P("规则文件无效：", "Invalid rule file:"),
                P("ℹ 未保存有效安装目录，无法重新执行兼容性预检。", "ℹ No valid installation directory is saved; the compatibility check cannot run."),
                P("”已经配置了自动成就规则，无需重复识别。", "\" already has automatic achievement rules; detection is not needed again."),
                P("✓ 已更新内置规则格式或模拟器路径。", "✓ Updated the built-in rule format or emulator path."),
                P("正在监听：", "Monitoring:"),
                P("兼容性预检：", "Compatibility check:"),
                P("若要更换规则，请先使用“移除自动成就规则”，再重新识别或导入规则文件。", "To replace the rules, remove the existing rules first, then detect or import again."),
                P("在以下目录未发现受支持的本地成就来源：", "No supported local achievement source was found in:"),
                P("目前可自动识别：", "Currently supported for automatic detection:"),
                P("• RUNE / CODEX 的 steam_emu.ini", "• RUNE / CODEX steam_emu.ini"),
                P("• Goldberg / GSE 的 steam_settings\\steam_appid.txt", "• Goldberg / GSE steam_settings\\steam_appid.txt"),
                P("• 旧版 Goldberg SteamEmu（已知 App ID 的无配置发布）", "• Legacy Goldberg SteamEmu (config-free release with a known App ID)"),
                P("• TENOKE 的 tenoke.ini", "• TENOKE tenoke.ini"),
                P("• RELOADED 的 steam_api.ini", "• RELOADED steam_api.ini"),
                P("• RPG Maker MV 的 Archeia / Greenworks 成就脚本", "• RPG Maker MV Archeia / Greenworks achievement scripts"),
                P("你仍可导入自定义 JSON 规则文件。", "You can still import a custom JSON rule file."),
                P("未找到可安装观察器的 RPG Maker 成就脚本。", "No RPG Maker achievement script suitable for the observer was found."),
                P("此游戏使用 RPG Maker MV / Greenworks 成就脚本。为记录游戏实际发出的成就事件，插件需要先备份并修改该脚本：", "This game uses an RPG Maker MV / Greenworks achievement script. To record achievement events actually emitted by the game, the extension must first back up and modify this script:"),
                P("是否继续？", "Continue?"),
                P("本地模拟器标识（非 Steam 库）", "Local emulator identifier (not in the Steam library)"),
                P("规则已保存，但当前没有可读取的本地成就来源，扩展无法自动弹窗或同步解锁。补全游戏的成就定义后，请重新检查本地状态；仅导入 SuccessStory 成就列表不能解决此问题。", "The rules were saved, but there is no readable local achievement source yet, so pop-ups and unlock synchronization are unavailable. Recheck local state after completing the definitions. Importing a SuccessStory list alone will not fix this."),
                P("下次通过 Playnite 启动此游戏时，扩展会记录游戏脚本实际发出的成就事件，并弹出通知。", "On the next Playnite launch, the extension will record achievement events emitted by the game script and show notifications."),
                P("下次通过 Playnite 启动此游戏时，扩展会监听模拟器的本地成就文件。", "On the next Playnite launch, the extension will monitor the emulator's local achievement file."),
                P("已识别模拟器，但当前无法自动弹出成就。", "The emulator was detected, but automatic achievement pop-ups are currently unavailable."),
                P("”自动配置规则。", "\" have been configured automatically."),
                P("游戏：“", "Game: \""),
                P("”\n识别结果：", "\"\nDetected source: "),
                P("请在 SuccessStory 中手动导入该游戏的 Steam 成就列表，以显示中文名称、图标并记录解锁时间。", "Import this game's Steam achievement list manually in SuccessStory to display names and icons and record unlock times."),
                P("自动配置失败：", "Automatic configuration failed:"),
                P("游戏正在运行，未自动修改成就定义。请退出游戏后重新扫描。", "The game is running; definitions were not changed. Exit the game and scan again."),
                P("缺少明确的 Steam App ID，无法安全补全成就定义。", "No unambiguous Steam App ID is available; definitions cannot be completed safely."),
                P("目标目录的 Steam App ID 不一致，未写入文件：", "The target directory has a different Steam App ID; no file was written: "),
                P("Steam 未返回此游戏的成就定义，未创建文件。", "Steam returned no achievement definitions for this game; no file was created."),
                P("ℹ 扫描期间成就定义已由其他程序创建，未覆盖：", "ℹ Another program created the definitions during the scan; they were not overwritten: "),
                P("✓ 已自动补全缺失的 GSE 成就定义：", "✓ Automatically created the missing GSE achievement definitions: "),
                P("；新增定义：", "; definitions added: "),
                P(" 项。\n仅补全定义，不会伪造已解锁状态；游戏仍须写入本地解锁记录。", " entries.\nDefinitions do not create unlocks; the game must still write local unlock records."),
                P("⚠ 自动补全 GSE 成就定义未完成：", "⚠ Automatic GSE definition completion did not finish: "),
                P("请检查目标目录是否已有部分新文件；现有成就定义不会被覆盖。", "Check whether the target directory contains any newly created files. Existing definitions were not overwritten."),
                P("游戏正在运行，未自动修改成就接口。请退出游戏后重新扫描。", "The game is running; its achievement interface was not changed. Exit the game and scan again."),
                P("⚠ 自动补全 RUNE/CODEX 成就接口未完成：", "⚠ Automatic RUNE/CODEX interface completion did not finish: "),
                P("不会猜测接口版本，也不会创建虚假的 achievements.ini。", "The interface version will not be guessed, and no artificial achievements.ini will be created."),
                P("缺少明确的 Steam App ID，未修改 RUNE/CODEX 配置。", "No unambiguous Steam App ID is available; the RUNE/CODEX configuration was not changed."),
                P("未找到 steam_emu.ini；不能补全 RUNE/CODEX 接口。", "steam_emu.ini was not found; the RUNE/CODEX interface cannot be completed."),
                P("相邻 Steam API DLL 实际为 GSE；未修改旧 RUNE/CODEX 配置。", "The adjacent Steam API DLL is actually GSE; the old RUNE/CODEX configuration was not changed."),
                P("steam_emu.ini 中的 App ID 与规则不一致；未修改文件。", "The App ID in steam_emu.ini does not match the rule; no file was changed."),
                P("无法从相邻原版 Steam API 文件唯一确定 SteamUserStats 版本。", "A unique SteamUserStats version could not be determined from the adjacent original Steam API file."),
                P("✓ 已自动补全 RUNE/CODEX 的 SteamUserStats 接口：", "✓ Automatically completed the RUNE/CODEX SteamUserStats interface: "),
                P("原文件备份：", "Original-file backup: "),
                P("游戏仍须自行写入 achievements.ini 中的 Achieved=1，才能触发弹窗。", "The game must still write Achieved=1 to achievements.ini for a pop-up to trigger."),
                P("无法完整扫描安装目录，未修改任何配置。", "The installation directory could not be scanned completely; no configuration was changed."),
                P("发现多个 steam_emu.ini，无法确定游戏实际使用的配置，未修改任何文件。", "Multiple steam_emu.ini files were found; the active game configuration is unknown, so no file was changed."),
                P("请先退出此游戏，再补全它的 GSE 成就定义。游戏运行时可能已把旧定义加载到内存。", "Exit this game before completing its GSE definitions. It may have loaded the old definitions into memory."),
                P("请先在 Playnite 中设置此游戏的安装目录。", "Set this game's installation directory in Playnite first."),
                P("正在读取 Steam 成就定义；完成后会显示写入前预览。", "Reading Steam achievement definitions; a preview will appear before writing."),
                P("此游戏未识别为 Goldberg / GSE。为避免写错游戏文件，成就定义补全只支持已经确认的 GSE 配置。", "This game was not identified as Goldberg / GSE. Definition completion requires a verified GSE configuration to avoid writing to the wrong game."),
                P("目标 steam_settings 中的 App ID 与游戏不一致；未写入任何文件：", "The target steam_settings has a different App ID; no file was written: "),
                P("Steam 未返回任何成就定义；未修改游戏文件。", "Steam returned no achievement definitions; game files were not changed."),
                P("游戏：“", "Game: \""),
                P("目标：", "Target: "),
                P("同时创建：", "Also create: "),
                P("Steam 返回：", "Steam returned: "),
                P(" 项。", " entries."),
                P(" 项；现有：", " entries; existing: "),
                P(" 项；拟新增：", " entries; to add: "),
                P("⚠ 现有定义无效，将在备份后重建。", "⚠ Existing definitions are invalid and will be rebuilt after a backup."),
                P("⚠ Steam 列表包含 ", "⚠ The Steam list contains "),
                P(" 项进度型成就；只补定义可能不足以让缺失统计上报的游戏解锁这些成就。", " progress-based achievements; definitions alone may not unlock them if the game does not report statistics."),
                P("只补全成就定义，不会伪造已解锁状态。游戏仍须通过模拟器实际写入解锁记录，插件才能自动弹窗。", "Only definitions will be completed; no unlock state is fabricated. The game must write real unlock records through the emulator before pop-ups can appear."),
                P("确认写入吗？", "Write these files?"),
                P("⚠ 已保留此游戏现有的非 GSE 自定义规则；请检查成就规则来源。", "⚠ Existing non-GSE custom rules were preserved; check the rule source."),
                P("⚠ 成就定义已写入，但规则路径更新失败：", "⚠ Definitions were written, but the rule path could not be updated: "),
                P("已补全成就定义：", "Achievement definitions completed: "),
                P("原文件备份：", "Original file backup: "),
                P("这不会使已经达成但从未写入本地状态的成就自动解锁。请通过 Playnite 启动游戏，之后用“查看成就来源健康状态”确认运行时文件是否出现 earned=true。", "This will not unlock achievements already completed but never written to local state. Launch the game through Playnite, then check Source Health for earned=true in the runtime file."),
                P("写入成就定义失败：", "Failed to write achievement definitions: "),
                P("补全 GSE 成就定义失败：", "Failed to complete GSE achievement definitions: "),
                P("请先退出游戏，再检查或补全成就接口。", "Exit the game before checking or completing its achievement interface."),
                P("未找到 steam_emu.ini；不能生成 RUNE/CODEX 配置。", "steam_emu.ini was not found; RUNE/CODEX configuration cannot be generated."),
                P("steam_emu.ini 没有有效 AppId；未修改文件。", "steam_emu.ini has no valid AppId; no file was changed."),
                P("此游戏虽然留有 RUNE/CODEX 的 steam_emu.ini，但相邻的当前 Steam API DLL 是 GSE。请使用“检查并补全 GSE 成就定义”，不要修改已失效的 RUNE 配置。", "This game retains a RUNE/CODEX steam_emu.ini, but the adjacent active Steam API DLL is GSE. Complete the GSE definitions instead of changing the obsolete RUNE configuration."),
                P("已找到 SteamUserStats 配置，无需补写。", "SteamUserStats is already configured; no change is needed."),
                P("模拟器：", "Emulator: "),
                P("RUNE/CODEX（未能区分）", "RUNE/CODEX (undetermined)"),
                P("监听路径：", "Monitored paths: "),
                P("只有游戏实际写入 Achieved=1，才会自动弹窗。", "Pop-ups require the game to write Achieved=1."),
                P("已校正成就监听路径，但无法从相邻原版 Steam API 文件唯一确定 SteamUserStats 接口版本。", "The monitored achievement path was corrected, but the SteamUserStats interface version could not be uniquely determined from an adjacent original Steam API file."),
                P("配置：", "Configuration: "),
                P("为避免猜错版本导致游戏异常，未修改 steam_emu.ini；也没有生成虚假的 achievements.ini。", "To avoid guessing a version and breaking the game, steam_emu.ini was not changed and no fake achievements.ini was created."),
                P("发现缺少 SteamUserStats 接口。", "The SteamUserStats interface is missing."),
                P("游戏：", "Game: "),
                P("拟补入：[Interfaces] 下的 SteamUserStats=", "Proposed addition under [Interfaces]: SteamUserStats="),
                P("会先备份原文件，保留原有编码与其他设置；不会改 DLL、存档或已解锁记录。补全接口不保证游戏会调用成就 API，也不能回放过去未上报的成就。", "The original file will be backed up; encoding and other settings will be preserved. DLLs, saves and unlock records will not be changed. Completing the interface does not guarantee the game calls the achievement API or replay past events."),
                P("确认补全吗？", "Complete the interface?"),
                P("⚠ 监听规则更新失败：", "⚠ Failed to update monitoring rules: "),
                P("已补全 SteamUserStats 接口。", "SteamUserStats interface completed."),
                P("备份：", "Backup: "),
                P("下次通过 Playnite 启动游戏后，请在达成一个新成就时检查 achievements.ini 是否写入 Achieved=1。没有该记录就仍无法自动弹窗。", "After the next Playnite launch, check whether achievements.ini records Achieved=1 for a new achievement. Pop-ups remain unavailable without that record."),
                P("RUNE/CODEX 配置检查失败：", "RUNE/CODEX configuration check failed: "),
                P("该游戏已有非 RUNE/CODEX 规则。请先检查或移除旧规则；未覆盖它。", "This game already has non-RUNE/CODEX rules. Check or remove the old rules first; they were not overwritten."),
                P("现有规则的 App ID 不同；未覆盖它。", "Existing rules use a different App ID and were not overwritten."),
                P("现有规则含自定义来源；为避免丢失它，未覆盖规则。", "Existing rules include custom sources and were preserved."),
                P("配置已包含 SteamUserStats；未修改文件。", "The configuration already contains SteamUserStats; no file was changed."),
                P("未找到完整的 [Interfaces] 段；未修改文件。", "No complete [Interfaces] section was found; no file was changed."),
                P("找到多个 App ID 相同的 GSE DLL 目录，且无法唯一确定紧邻游戏主程序的目录。未写入任何文件：", "Multiple GSE DLL directories share this App ID, and the one beside the game executable cannot be identified uniquely. No file was written: "),
                P("未找到 App ID 为 ", "No configuration directory with App ID "),
                P("、且与 steam_api(64).dll 对应的配置目录。请检查游戏实际加载的 DLL 与 steam_appid.txt；未写入任何文件。", " matches steam_api(64).dll. Check the DLL actually loaded by the game and steam_appid.txt; no file was written."),
                P("现有定义文件过大。", "The existing definition file is too large."),
                P("现有定义不是 JSON 数组。", "Existing definitions are not a JSON array."),
                P("现有定义包含空 ID 或重复 ID。", "Existing definitions contain an empty or duplicate ID."),
                P("✓ 已备份原有成就脚本，并添加只记录游戏真实成就事件的观察器。不会修改 Steam 接口调用。", "✓ The original achievement script was backed up and an observer for real game achievement events was added. Steam API calls were not changed."),
                P("⚠ 尚未安装 RPG Maker 成就事件观察器；请重新执行自动配置。", "⚠ The RPG Maker achievement observer is not installed; run automatic configuration again."),
                P("ℹ 事件在游戏触发时写入本地日志。已有存档不会被推测为已解锁；游戏未调用的成就也不会自动解锁。", "ℹ Events are written to a local log when triggered by the game. Existing saves are not inferred as unlocked, and achievements never called by the game cannot unlock automatically."),
                P("⛔ 当前无法自动弹窗：未发现 steam_settings\\achievements.json，也未发现规则监听的本地成就状态文件。只导入 Steam 成就列表不会产生弹窗。可使用“检查并补全 GSE 成就定义”；扩展会预览目标，并在确认后备份或创建定义，但仍需游戏实际写入解锁记录。", "⛔ Automatic pop-ups are unavailable: neither steam_settings\\achievements.json nor a monitored local achievement-state file was found. Importing a Steam list alone cannot create pop-ups. Run detection again to try automatic definition completion; the game must still write unlock records."),
                P("⚠ 未发现 steam_settings\\achievements.json，但已有可读取的本地成就状态文件。扩展仍可监听现有记录；未来新成就是否会写入，需要在游戏中验证。可使用“检查并补全 GSE 成就定义”预览并补全缺失定义。", "⚠ steam_settings\\achievements.json was not found, but a readable local achievement-state file exists. Existing records can still be monitored; verify new unlocks in-game. Run detection again to complete missing definitions automatically."),
                P("ℹ 已发现 GSE 成就定义和本地状态文件；仍须确认状态文件在游戏解锁时写入 earned=true，才能证明自动弹窗链路有效。", "ℹ GSE definitions and a local state file were found. Verify that the file records earned=true when the game unlocks an achievement to confirm the pop-up path."),
                P("⚠ 已发现 GSE 成就定义，但尚未发现本地解锁状态。这只说明成就列表可用，不证明游戏会调用成就接口或模拟器会写入解锁记录。首次实际解锁后请检查来源健康状态。", "⚠ GSE definitions were found, but no local unlock state exists yet. A list alone does not prove the game calls the achievement API or that the emulator writes unlock records. Check Source Health after a real unlock."),
                P("⚠ RUNE/CODEX 配置未声明 SteamUserStats 接口；成就上报存在风险，但不能仅凭这一项断定一定失败。", "⚠ RUNE/CODEX does not declare SteamUserStats; achievement reporting may fail, although this alone is not conclusive."),
                P("相邻原版 Steam API 未提供唯一接口版本，扩展不会猜测。", "The adjacent original Steam API does not provide a unique interface version; the extension will not guess."),
                P("检测到可补全的接口版本 ", "A usable interface version was found: "),
                P("；可使用右键菜单“检查并补全 RUNE/CODEX 成就接口”。", "; use the right-click action to complete the RUNE/CODEX interface."),
                P("✓ RUNE/CODEX 配置声明了 SteamUserStats 接口；仍需实际解锁记录验证。", "✓ RUNE/CODEX declares SteamUserStats; a real unlock record is still needed for verification."),
                P("⚠ RUNE 已创建成就状态文件，但其中只有 Count=0，尚未上报任何成就。若游戏已经通过明确的剧情成就条件后仍保持此状态，说明该发布的成就回调不可用，扩展无法自动解锁。", "⚠ RUNE created an achievement-state file, but it still shows Count=0 and no achievements. If this persists after a clear story achievement, this release may not provide working callbacks, so the extension cannot unlock it automatically."),
                P("✓ RUNE 本地状态文件已经包含已上报的成就，自动监听可用。", "✓ The RUNE state file contains reported achievements; automatic monitoring is available."),
                P("ℹ RUNE 本地状态文件已初始化，但尚未发现已解锁的成就。", "ℹ The RUNE state file is initialized, but no unlocked achievements were found yet."),
                P("⚠ 风险提示：本地 Steam 接口 DLL 的时间明显早于游戏主程序。该发布可能混用了不同版本，成就接口虽能初始化却可能无法接收回调；这不是确定结论，但建议在出现 Count=0 时优先判定为发布兼容性问题。", "⚠ Compatibility risk: the local Steam API DLL is much older than the game executable. Mixed versions may initialize but fail to receive achievement callbacks. This is not conclusive, but consider release compatibility when Count=0 persists."),
                P("ℹ 尚未生成本地解锁状态文件；对刚开始游玩的游戏这通常正常，但若已完成明确成就条件后仍不存在，则说明该发布没有可供本扩展读取的成就上报。", "ℹ No local unlock-state file exists yet. This can be normal for a new game; if it remains absent after a clear achievement condition, this release provides no readable achievement report."),
                P("✓ 预检完成：已找到可监听的本地成就状态。", "✓ Compatibility check complete: a monitorable local achievement state was found."),
                P("要移除“", "Remove the automatic rules for \""),
                P("”的自动成就规则吗？现有的 SuccessStory 记录和本地成就历史不会被删除。", "\"? Existing SuccessStory records and local achievement history will not be deleted."),
                P("规则已移除，但游戏脚本在安装观察器后又发生变化，因此未自动覆盖它。原始备份仍在：", "The rules were removed, but the game script changed after installing the observer, so it was not overwritten. Original backup: "),
                P("恢复游戏原始成就脚本时遇到问题，请保留备份并检查：", "There was a problem restoring the original achievement script. Keep the backup and check: "),
                P("无法加载成就规则：", "Could not load achievement rules: "),
                P("另一个游戏正在由本扩展监听。请先退出该游戏，再执行补扫。", "This extension is monitoring another game. Exit it before rescanning."),
                P("已读取游戏当前的本地成就状态，并完成补扫与 SuccessStory 同步。只有状态文件中已标记为解锁的成就会被记录。", "The current local achievement state was rescanned and synchronized with SuccessStory. Only achievements marked as unlocked in the state file were recorded."),
                P("补扫失败：", "Rescan failed: "),
                P("本地成就已解锁，但同步 SuccessStory 失败：", "A local achievement unlocked, but SuccessStory synchronization failed: "),
                P("成就已记录，但 SuccessStory 主题数字刷新失败：", "The achievement was recorded, but the SuccessStory theme counter did not refresh: "),
                P("本地成就已解锁，但写入 SuccessStory 记录失败：", "A local achievement unlocked, but writing its SuccessStory record failed: "),
                P("本地成就已写入 SuccessStory，但界面刷新失败：", "The achievement was written to SuccessStory, but the interface did not refresh: "),
                P("此游戏尚未导入成就规则文件。", "No achievement rule file has been imported for this game."),
                P("规则名称：", "Rule name: "),
                P("未命名", "Unnamed"),
                P("监听来源：", "Monitored sources: "),
                P("游戏监听：", "Game monitoring: "),
                P("运行中", "Running"),
                P("未运行；须通过 Playnite 启动游戏才会实时监听", "Not running; real-time monitoring requires launching the game through Playnite"),
                P("【来源状态】", "[Source status]"),
                P("⚠ 未生成或无法访问：游戏目前没有可监听的本地状态。", "⚠ Missing or inaccessible: the game currently has no monitorable local state."),
                P("⚠ 发现同名 .ini 状态文件，但此 JSON 规则不会读取它：", "⚠ A same-name .ini state file exists, but this JSON rule does not read it: "),
                P("✓ 文件存在；最后写入：", "✓ File exists; last write: "),
                P("；大小：", "; size: "),
                P(" 字节", " bytes"),
                P("当前读取到已解锁 ID：", "Currently detected unlocked IDs: "),
                P("ℹ 文件可读取，但尚未匹配到任何已解锁标记。", "ℹ The file is readable, but no unlocked markers matched yet."),
                P("【本扩展记录】", "[Extension records]"),
                P("已记录本地解锁：", "Recorded local unlocks: "),
                P("已通知 ID：", "Notified IDs: "),
                P("（已通知的成就不会重复弹窗）", "(notified achievements will not pop up again)"),
                P("来源中可立即补同步的解锁：", "Unlocks available for immediate reconciliation: "),
                P("【SuccessStory 同步校验】", "[SuccessStory synchronization check]"),
                P("【兼容性预检】", "[Compatibility check]"),
                P("ℹ 未保存有效安装目录，无法执行接口预检。", "ℹ No valid installation directory is saved; interface checks cannot run."),
                P("规则文件：", "Rule file: "),
                P("ℹ SuccessStory 的主题计数暂不可读取。", "ℹ The SuccessStory theme counter cannot be read yet."),
                P("未设置", "Not set"),
                P("主题当前游戏：", "Theme current game: "),
                P("；主题绑定计数：", "; theme-bound count: "),
                P("（与本游戏一致）", "(matches this game)"),
                P("（当前不是本游戏，不用于核对）", "(another game is selected; not used for comparison)"),
                P("⚠ 读取主题计数失败：", "⚠ Failed to read the theme counter: "),
                P("⚠ 尚未定位实际 GSE 配置目录。请重新执行自动识别，以便核对成就定义是否紧邻 Steam API DLL。", "⚠ The active GSE configuration directory is not known. Run automatic detection again to check that definitions are beside the Steam API DLL."),
                P("✓ 成就定义目录位于 Steam API DLL 旁。", "✓ The achievement-definition directory is beside the Steam API DLL."),
                P("⚠ 此成就定义目录旁没有 Steam API DLL；游戏可能没有读取它。", "⚠ No Steam API DLL is beside this definition directory; the game may not read it."),
                P("⚠ 规则 App ID：", "⚠ Rule App ID: "),
                P("；配置文件 App ID：", "; configuration App ID: "),
                P("。身份不一致时无法可靠匹配成就。", ". Achievements cannot be matched reliably when these IDs differ."),
                P("⚠ 缺少成就定义：", "⚠ Missing achievement definitions: "),
                P("。可使用“检查并补全 GSE 成就定义”。", ". Run automatic detection to try completing GSE definitions."),
                P("文件超过 16 MB", "File exceeds 16 MB"),
                P("不是成就定义数组", "Not an achievement-definition array"),
                P("成就定义：", "Achievement definitions: "),
                P(" 个有效且不重复的 API ID。", " valid, unique API IDs."),
                P("⚠ 可尝试补全。", "⚠ Completion may be possible."),
                P("⚠ 成就定义无法解析：", "⚠ Could not parse achievement definitions: "),
                P("⚠ 未找到该游戏的 SuccessStory 手动成就列表。请先在 SuccessStory 中添加或导入列表。", "⚠ No SuccessStory manual achievement list was found for this game. Add or import one in SuccessStory first."),
                P("⚠ SuccessStory 列表格式无法识别。", "⚠ The SuccessStory list format was not recognized."),
                P("✓ 已找到 SuccessStory 手动列表：", "✓ SuccessStory manual list found: "),
                P(" 个成就；已显示解锁：", " achievements; displayed unlocks: "),
                P("本扩展历史 ID 与 ApiName 匹配：", "Extension history IDs matching ApiName: "),
                P("⚠ 有 ", "⚠ "),
                P(" 个本地 ID 未能匹配 SuccessStory 的 ApiName；这些成就会弹窗，但无法写入 SuccessStory。", " local IDs do not match SuccessStory ApiName IDs; they may pop up but cannot be written to SuccessStory."),
                P("✓ 已记录的本地成就均可写入 SuccessStory。", "✓ All recorded local achievements can be written to SuccessStory."),
                P("⚠ 读取 SuccessStory 校验信息失败：", "⚠ Failed to read SuccessStory validation data: "),
                P("成就已解锁", "Achievement unlocked"),
                P("已解锁", "Unlocked"),
            };
            items.Sort((left, right) => right.Key.Length.CompareTo(left.Key.Length));
            return items;
        }
    }
}
